version: '3.5'

services:
  ngx:
    container_name: simple-table
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 4200:4200